quarkus.thread.virtual.enabled=true
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/df_agent_db
quarkus.datasource.username=df_dev_user
quarkus.datasource.password=df_dev_secret
bronze.root=/data/bronze